### ISSUE TITLE
Vision for cetmix_tower_template_odoo

### ISSUE THREAD

**Issue by norlinhenrik** [cetmix/cetmix-tower#57]
@ivs-cetmix 
What is your vision for `cetmix_tower_template_odoo`?
Do you consider it to be a **template** or a **standard**?
Should the data records be updated or not when the module is updated?

I prefer **Infrastructure as Code** (IaC) and documenting changes by commits.

* Standard variables and global values may be defined in a CSV. Then a script can create the XML data files.
* Standard data records may be updatable and READONLY.
* Changes may need migration scripts.

Standarized processes and automation is the key value of [rackn.com](https://rackn.com/). They have concepts similar to flight plans ([wizards](https://www.youtube.com/watch?v=osv6vHFEhk0&t=60s)) running commands (tasks). And ideas to implement in Cetmix Tower:

* A wizard has parameter fields.
* The tasks are logged, AND you see the logging in real time.
* The user may set variables / parameters and run standarized wizards.

Would you like to use `cetmix_tower_template_odoo` as a standard for your clients, or is this just a template to help others getting started?

**Comment by ivs-cetmix** [comment]
Hi @norlinhenrik, just not this to look like it's a stalled issue 😄 

Most of this is either planned or already being developed or is done.
Regarding the IaC we are working on the full YAML support for most of the entities so this should be an answer. 
First steps are done in #103 so you are welcome to review and contribute!

**Comment by ivs-cetmix** [comment]
Hey @norlinhenrik this is now done with the `cetmix_tower_yaml` module, so I close the issue. Thank you for your contribution!
